version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli-node

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: composer install --prefer-dist

      - run:
          name: Validate Code
          command: ./bin/phpcs

      - run:
          name: Test
          command: ./bin/phpunit
